name: M2MEG-RNAseq-TP3-bash

channels:
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
  - defaults
  - bioconda
  - conda-forge

dependencies:
  - jupyterlab=2
  - nbresuse
  - python>=3.7
  - pip
  - nodejs
  - fastqc
  - fastp
  - bowtie
  - samtools
  - multiqc
  - qualimap
  - bedtools
  - htseq
  - sra-tools
  - libgomp
  - r-irkernel
  - r-base>=3.6
  - r-tidyverse 
  - r-Matrix
  - r-lattice
  - r-fdrtool
  - r-rpart
  - r-RSQLite
  - r-gplots
  - r-locfit
  - pip:
    - bash_kernel
